---@meta

---@class ImGuiWindowFlags
---@field None integer 
---@field NoTitleBar integer 
---@field NoResize integer 
---@field NoMove integer 
---@field NoScrollbar integer 
---@field NoScrollWithMouse integer 
---@field NoCollapse integer 
---@field AlwaysAutoResize integer 
---@field NoBackground integer 
---@field NoSavedSettings integer 
---@field NoMouseInputs integer 
---@field MenuBar integer 
---@field HorizontalScrollbar integer 
---@field NoFocusOnAppearing integer 
---@field NoBringToFrontOnFocus integer 
---@field AlwaysVerticalScrollbar integer 
---@field AlwaysHorizontalScrollbar integer 
---@field NoNavInputs integer 
---@field NoNavFocus integer 
---@field UnsavedDocument integer 
---@field NoNav integer 
---@field NoDecoration integer 
---@field NoInputs integer 
ImGuiWindowFlags = {}
