#pragma once

#define ICON_MIN_MS 0xE037
#define ICON_MAX_MS 0xF8B6

#define ICON_MS_ADD                                      "\xEE\x85\x85" // U+E145
#define ICON_MS_BACKGROUND_REPLACE                       "\xEF\x88\x8A" // U+F20A
#define ICON_MS_BACKSPACE                                "\xEE\x85\x8A" // U+E14A
#define ICON_MS_BLOCK                                    "\xEF\x82\x8C" // U+F08C
#define ICON_MS_BOOK                                     "\xEE\xA1\xAE" // U+E86E
#define ICON_MS_BRIGHTNESS_1                             "\xEE\x8F\xBA" // U+E3FA
#define ICON_MS_BROWSE                                   "\xEE\xAC\x93" // U+EB13
#define ICON_MS_CHECK_CIRCLE                             "\xEF\x82\xBE" // U+F0BE
#define ICON_MS_CHECK_CIRCLE_OUTLINE                     "\xEF\x82\xBE" // U+F0BE
#define ICON_MS_CLEAR                                    "\xEE\x97\x8D" // U+E5CD
#define ICON_MS_CLEAR_ALL                                "\xEE\x82\xB8" // U+E0B8
#define ICON_MS_CLOUD_DOWNLOAD                           "\xEE\x8B\x80" // U+E2C0
#define ICON_MS_CODE                                     "\xEE\xA1\xAF" // U+E86F
#define ICON_MS_CONTENT_COPY                             "\xEE\x85\x8D" // U+E14D
#define ICON_MS_DELETE                                   "\xEE\xA4\xAE" // U+E92E
#define ICON_MS_DISPLAY_SETTINGS                         "\xEE\xAE\x97" // U+EB97
#define ICON_MS_DOWNLOAD                                 "\xEF\x82\x90" // U+F090
#define ICON_MS_ERROR                                    "\xEF\xA2\xB6" // U+F8B6
#define ICON_MS_EXTENSION                                "\xEE\xA1\xBB" // U+E87B
#define ICON_MS_FILE_COPY                                "\xEE\x85\xB3" // U+E173
#define ICON_MS_FILTER_LIST                              "\xEE\x85\x92" // U+E152
#define ICON_MS_FOLDER                                   "\xEE\x8B\x87" // U+E2C7
#define ICON_MS_HELP                                     "\xEE\xA3\xBD" // U+E8FD
#define ICON_MS_HOME_APP_LOGO                            "\xEE\x8A\x95" // U+E295
#define ICON_MS_HOURGLASS_BOTTOM                         "\xEE\xA9\x9C" // U+EA5C
#define ICON_MS_HOURGLASS_EMPTY                          "\xEE\xA2\x8B" // U+E88B
#define ICON_MS_HOURGLASS_TOP                            "\xEE\xA9\x9B" // U+EA5B
#define ICON_MS_INFO                                     "\xEE\xA2\x8E" // U+E88E
#define ICON_MS_LIST                                     "\xEE\xA2\x96" // U+E896
#define ICON_MS_MEMORY                                   "\xEE\x8C\xA2" // U+E322
#define ICON_MS_MESSAGE                                  "\xEE\x83\x89" // U+E0C9
#define ICON_MS_MORE_VERT                                "\xEE\x97\x94" // U+E5D4
#define ICON_MS_NOTIFICATIONS                            "\xEE\x9F\xB5" // U+E7F5
#define ICON_MS_NOTIFICATIONS_ACTIVE                     "\xEE\x9F\xB7" // U+E7F7
#define ICON_MS_NOTIFICATIONS_OFF                        "\xEE\x9F\xB6" // U+E7F6
#define ICON_MS_NOTIFICATIONS_PAUSED                     "\xEE\x9F\xB8" // U+E7F8
#define ICON_MS_OPACITY                                  "\xEE\xA4\x9C" // U+E91C
#define ICON_MS_OPEN_IN_NEW                              "\xEE\xA2\x9E" // U+E89E
#define ICON_MS_PALETTE                                  "\xEE\x90\x8A" // U+E40A
#define ICON_MS_PLAY_ARROW                               "\xEE\x80\xB7" // U+E037
#define ICON_MS_PRIORITY_HIGH                            "\xEE\x99\x85" // U+E645
#define ICON_MS_RADIO_BUTTON_CHECKED                     "\xEE\xA0\xB7" // U+E837
#define ICON_MS_RADIO_BUTTON_UNCHECKED                   "\xEE\xA0\xB6" // U+E836
#define ICON_MS_REFRESH                                  "\xEE\x97\x95" // U+E5D5
#define ICON_MS_SEARCH                                   "\xEE\xBD\xBA" // U+EF7A
#define ICON_MS_SETTINGS                                 "\xEE\xA2\xB8" // U+E8B8
#define ICON_MS_STAR                                     "\xEF\x82\x9A" // U+F09A
#define ICON_MS_SYNC                                     "\xEE\x98\xA7" // U+E627
#define ICON_MS_SYRINGE                                  "\xEE\x84\xB3" // U+E133
#define ICON_MS_TERMINAL                                 "\xEE\xAE\x8E" // U+EB8E
#define ICON_MS_TOGGLE_OFF                               "\xEE\xA7\xB5" // U+E9F5
#define ICON_MS_TOGGLE_ON                                "\xEE\xA7\xB6" // U+E9F6
#define ICON_MS_TUNE                                     "\xEE\x90\xA9" // U+E429
#define ICON_MS_UPDATE                                   "\xEE\xA4\xA3" // U+E923
#define ICON_MS_VOLUME_MUTE                              "\xEE\x81\x8E" // U+E04E
#define ICON_MS_VOLUME_UP                                "\xEE\x81\x90" // U+E050
#define ICON_MS_WARNING                                  "\xEF\x82\x83" // U+F083
