name: Generate Lua Docs

on:
  push:
    branches:
      - main
    paths:
      - "scripts/lua_doc_gen.py"
      - "src/core/lua_scripting/libs/**"
  workflow_dispatch:

concurrency:
  group: ylp_docgen-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v7

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12.x"

    - name: Run Generator
      run: |
        cd ./scripts
        python lua_doc_gen.py

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/
        git diff --cached --quiet || git commit -m "[noci] docs(Lua API): update Lua docs"
        git push
